vault:
  server: http://vault.vault.svc.cluster.local:8200
  kvPath: secret
  authMountPath: kubernetes
  role: eso-role

externalSecrets:
  serviceAccountName: external-secrets
  namespace: external-secrets
