apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kvPath | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authMountPath | quote }}
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName | quote }}
            namespace: {{ .Values.externalSecrets.namespace | quote }}
