{{- if .Values.apps.secretsConfig.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: charts/secrets-config
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.secretsConfig.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
