apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.productpage.replicas }}
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
        - name: productpage
          image: "{{ .Values.productpage.image }}:{{ .Values.productpage.tag }}"
          ports:
            - containerPort: {{ .Values.productpage.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: productpage
  ports:
    - port: 9080
      targetPort: {{ .Values.productpage.port }}
      nodePort: {{ .Values.service.productpageNodePort }}
